### ISSUE TITLE
panicked at 'RUST_COMPILER_RT_ROOT is not set'

### ISSUE THREAD

**Issue by bigfish24** [rust-lang-nursery/compiler-builtins#295] opened 2019-05-17 01:02 UTC
```
rustc -V
rustc 1.36.0-nightly (af98304b9 2019-05-11)

xargo -V
xargo 0.3.14
cargo 1.36.0-nightly (759b6161a 2019-05-06)

compiler_builtins v0.1.15
```
Trying to compile Rust for an iOS SDK.

**Comment by bigfish24** [comment] 2019-05-17 01:16
If I am looking over the recent commits correctly from 0.1.14 to 0.1.15 this introduced the ENV: https://github.com/rust-lang-nursery/compiler-builtins/commit/aa41e0d25fcb2b11b9b5c269846dd70547f2a787 and I need to then point to the `compiler-rt` folder in the LLVM source (https://github.com/llvm/llvm-project/tree/master/compiler-rt)?

**Comment by alexcrichton** [comment] 2019-05-17 14:46
Thanks for the report! In an effort to deduplicate the compiler-rt source used by rustc this is now required when compiling with the `c` feature enabled. Would you be able to detail a bit why you're compiling with the `c` feature, and would it be possible to turn it off?

**Comment by BaoshanPang** [comment] 2019-05-25 02:40
I am seeing this problem when build the rust from source code.

**Comment by mati865** [comment] 2019-05-25 08:35
Could you give more details?
Are you building tarball or git checkout?
Which version or commit are you building?
Have you upgraded Cargo.lock  (not like you should)?

**Comment by chesterliliang** [comment] 2019-06-18 07:52
I am trying to complie a static lib for arm cortex-m0.
only has a test function:

#![no_std]
#![feature(compiler_builtins_lib)]

extern crate compiler_builtins;

#[no_mangle]
pub unsafe extern "C" fn add_rust(a:u32,b:u32) -> u32{
    a+b
}

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = ["c"]

ChestersdeMacBook-Pro:alg_add chester$ cargo build --target thumbv6m-none-eabi
   Compiling compiler_builtins v0.1.16 (https://github.com/rust-lang-nursery/compiler-builtins#5e06435c)
error: failed to run custom build command for `compiler_builtins v0.1.16 (https://github.com/rust-lang-nursery/compiler-builtins#5e06435c)`

Caused by:
  process didn't exit successfully: `/Users/chester/alg_add/target/debug/build/compiler_builtins-3dc7e671716fb0c4/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:compiler-rt=/Users/chester/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/5e06435/compiler-rt

--- stderr
thread 'main' panicked at 'RUST_COMPILER_RT_ROOT is not set', /Users/chester/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/5e06435/build.rs:420:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

ChestersdeMacBook-Pro:alg_add chester$ rustc -V
rustc 1.37.0-nightly (d132f544f 2019-06-07)
ChestersdeMacBook-Pro:alg_add chester$ cargo -V
cargo 1.37.0-nightly (545f35425 2019-05-23)
ChestersdeMacBook-Pro:alg_add chester$

**Comment by alexcrichton** [comment] 2019-06-18 17:25
@chesterliliang yes you'll have to provide this env var when building compiler-builtins and provide your own source code for compiler-builtins.

I'm gonna go ahead and close this since it's currently working as intended.

**Closed by alexcrichton** 2019-06-18 17:25 UTC
